modLoader = "javafml"
loaderVersion = "[41,)"
#issueTrackerURL = ""
license = "ARR"

[[mods]]
modId = "ftbpc"
version = "${version}"
displayName = "FTB Pack Companion"
authors = "FTB Team"
description = '''
A Modpack developers best friend
'''
#logoFile = ""

[[dependencies.ftbpc]]
modId = "forge"
mandatory = true
versionRange = "${loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbpc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
